name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: nothing
    - run: |
        if [[ "${{ steps.nothing.outputs.stored }}" == "true" ]]; then
          echo "unexpectedly stored to cache"
          exit 1
        fi
      shell: bash
    - run: |
        echo "modified" >> LICENSE
        echo "modified" >> CHANGELOG.md
      shell: bash
    - uses: ./
      id: modified
    - run: |
        if [[ "${{ steps.modified.outputs.stored }}" != "true" ]]; then
          echo "not stored to cache"
          exit 1
        fi
        if [[ "${{ steps.modified.outputs.files }}" == "" ]]; then
          echo "no files added"
          exit 1
        fi
        if [[ "${{ steps.modified.outputs.cache-key }}" == "" ]]; then
          echo "empty cache key"
          exit 1
        fi
      shell: bash
    - run: rm LICENSE CHANGELOG.md
      shell: bash
    - uses: actions/cache/restore@v4
      with:
        path: ${{ steps.modified.outputs.files }}
        key: ${{ steps.modified.outputs.cache-key }}
        fail-on-cache-miss: true
    - run: |
        if [ ! -f "LICENSE" ]; then
          echo "LICENSE does not exist"
          exit 1
        fi
        if [ ! -f "CHANGELOG.md" ]; then
          echo "CHANGELOG.md does not exist"
          exit 1
        fi
      shell: bash
    - uses: prantlf/delete-cache-action@v3
      with:
        key: shelved-changes-${{ github.sha }}
    - uses: prantlf/publish-release-action@v1
      if: ${{ github.ref_name == 'master' }}
      with:
        no-bump: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
